# Generated by Django 5.2.16 on 2026-07-22 02:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geometria')),
                ('sector_type', models.CharField(blank=True, max_length=100, verbose_name='tipo')),
            ],
        ),
        migrations.CreateModel(
            name='AffectedBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200, verbose_name='referencia')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='geometria')),
                ('damage_level', models.CharField(blank=True, max_length=100, verbose_name='nivel de dano')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedRoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=200, verbose_name='via')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='geometria')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='bloqueo activo')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geometria')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='nivel')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('hospital_type', models.CharField(blank=True, max_length=100, verbose_name='tipo')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='ubicacion')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='direccion')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('total_capacity', models.PositiveIntegerField(default=0, verbose_name='capacidad total')),
                ('available_capacity', models.PositiveIntegerField(default=0, verbose_name='capacidad disponible')),
                ('is_operational', models.BooleanField(default=True, verbose_name='operativo')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'hospital',
                'verbose_name_plural': 'hospitales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='geometria')),
                ('is_open', models.BooleanField(default=True, verbose_name='abierta')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='ubicacion')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='direccion')),
                ('manager', models.CharField(blank=True, max_length=200, verbose_name='responsable')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('total_capacity', models.PositiveIntegerField(default=0, verbose_name='capacidad total')),
                ('registered_people', models.PositiveIntegerField(default=0, verbose_name='personas registradas')),
                ('is_operational', models.BooleanField(default=True, verbose_name='operativo')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'refugio',
                'verbose_name_plural': 'refugios',
                'ordering': ['name'],
            },
        ),
    ]
