# Generated by Django 5.2.16 on 2026-07-22 02:24

import alertas.models
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_tracking_code', models.CharField(default=alertas.models.generate_tracking_code, editable=False, max_length=15, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('person_name', models.CharField(blank=True, max_length=200, verbose_name='nombre de la persona')),
                ('identification_number', models.CharField(blank=True, max_length=30, verbose_name='identificacion')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('alternative_phone', models.CharField(blank=True, max_length=30, verbose_name='telefono alternativo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electronico')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='ubicacion')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitud')),
                ('address_reference', models.CharField(blank=True, max_length=300, verbose_name='direccion o referencia')),
                ('emergency_type', models.CharField(choices=[('trapped_person', 'Persona atrapada'), ('injured_person', 'Persona herida'), ('collapsed_building', 'Edificacion colapsada'), ('fire', 'Incendio'), ('blocked_road', 'Via bloqueada'), ('gas_leak', 'Fuga de gas'), ('electrical_risk', 'Riesgo electrico'), ('missing_person', 'Persona desaparecida'), ('other', 'Otra emergencia')], max_length=30, verbose_name='tipo de emergencia')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('estimated_affected_people', models.PositiveIntegerField(default=1, verbose_name='personas afectadas')),
                ('injured_people', models.PositiveIntegerField(default=0, verbose_name='personas heridas')),
                ('has_children', models.BooleanField(default=False, verbose_name='hay ninos')),
                ('has_older_adults', models.BooleanField(default=False, verbose_name='hay adultos mayores')),
                ('has_people_with_disabilities', models.BooleanField(default=False, verbose_name='hay personas con discapacidad')),
                ('building_condition', models.CharField(choices=[('unknown', 'No informado'), ('stable', 'Estable'), ('damaged', 'Danada'), ('partially_collapsed', 'Colapso parcial'), ('collapsed', 'Colapsada')], default='unknown', max_length=30, verbose_name='estado de la edificacion')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='medium', max_length=10, verbose_name='prioridad')),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('verifying', 'En verificacion'), ('verified', 'Verificada'), ('assigned', 'Asignada'), ('in_progress', 'En atencion'), ('rescued', 'Rescatada'), ('transferred', 'Trasladada'), ('closed', 'Cerrada'), ('false_alert', 'Falsa alerta'), ('cancelled', 'Cancelada')], default='received', max_length=20, verbose_name='estado')),
                ('audio_storage_path', models.CharField(blank=True, max_length=500)),
                ('image_storage_path', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='alertas_ale_status_9f4c75_idx'), models.Index(fields=['-created_at'], name='alertas_ale_created_1c33bc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('estimated_affected_people__gte', 1)), name='alert_affected_people_positive')],
            },
        ),
    ]
