# Generated by Django 5.2.16 on 2026-07-22 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='observaciones internas'),
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('status', 'Cambio de estado'), ('priority', 'Cambio de prioridad'), ('observation', 'Observacion interna')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=100)),
                ('new_value', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='alertas.alert')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial de alerta',
                'verbose_name_plural': 'historial de alertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
