# Generated by Django 5.2.16 on 2026-07-22 02:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RescueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='codigo')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='institucion')),
                ('current_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='ubicacion actual')),
                ('operational_status', models.CharField(default='available', max_length=50, verbose_name='estado operativo')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='especialidad')),
                ('vehicle_available', models.BooleanField(default=False, verbose_name='vehiculo disponible')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'equipo de rescate',
                'verbose_name_plural': 'equipos de rescate',
                'ordering': ['name'],
            },
        ),
    ]
