# Generated by Django 5.2.16 on 2026-07-22 03:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_alert_internal_notes_alerthistory'),
        ('rescates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueteam',
            name='member_count',
            field=models.PositiveIntegerField(default=0, verbose_name='integrantes'),
        ),
        migrations.AddField(
            model_name='rescueteam',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefono'),
        ),
        migrations.AddField(
            model_name='rescueteam',
            name='responsible',
            field=models.CharField(blank=True, max_length=200, verbose_name='responsable'),
        ),
        migrations.AlterField(
            model_name='rescueteam',
            name='operational_status',
            field=models.CharField(choices=[('available', 'Disponible'), ('assigned', 'Asignado'), ('in_operation', 'En operacion'), ('out_of_service', 'Fuera de servicio')], default='available', max_length=50, verbose_name='estado operativo'),
        ),
        migrations.AlterField(
            model_name='rescueteam',
            name='specialty',
            field=models.CharField(blank=True, max_length=150, verbose_name='capacidad o especialidad'),
        ),
        migrations.CreateModel(
            name='RescueAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('assigned', 'Asignada'), ('accepted', 'Aceptada'), ('en_route', 'En ruta'), ('on_site', 'En sitio'), ('rescuing', 'En rescate'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='assigned', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('departure_at', models.DateTimeField(blank=True, null=True)),
                ('arrival_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, verbose_name='resultado')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_assignments', to='alertas.alert')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescue_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rescates.rescueteam')),
            ],
            options={
                'verbose_name': 'asignacion de rescate',
                'verbose_name_plural': 'asignaciones de rescate',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rescates.rescueassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=150, verbose_name='nombres')),
                ('last_names', models.CharField(blank=True, max_length=150, verbose_name='apellidos')),
                ('identification_number', models.CharField(blank=True, max_length=30, verbose_name='identificacion')),
                ('approximate_age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='edad aproximada')),
                ('sex', models.CharField(blank=True, max_length=30, verbose_name='sexo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('health_status', models.CharField(blank=True, max_length=100, verbose_name='estado de salud')),
                ('rescue_status', models.CharField(choices=[('reported', 'Reportada'), ('located', 'Localizada'), ('in_care', 'En atencion'), ('rescued', 'Rescatada'), ('transferred', 'Trasladada'), ('reunited', 'Reunificada'), ('not_located', 'No localizada'), ('deceased', 'Fallecida')], default='reported', max_length=20)),
                ('transfer_location', models.CharField(blank=True, max_length=250, verbose_name='lugar de traslado')),
                ('rescued_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('photo_storage_path', models.CharField(blank=True, max_length=500)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='alertas.alert')),
            ],
            options={
                'verbose_name': 'victima',
                'verbose_name_plural': 'victimas',
                'ordering': ['last_names', 'first_names'],
            },
        ),
    ]
