# Generated by Django 5.2.16 on 2026-07-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0001_initial'),
        ('rescates', '0002_rescueteam_member_count_rescueteam_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='safe_place',
            field=models.CharField(blank=True, max_length=250, verbose_name='otro lugar seguro'),
        ),
        migrations.AddField(
            model_name='victim',
            name='transfer_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_victims', to='infraestructura.hospital'),
        ),
        migrations.AddField(
            model_name='victim',
            name='transfer_shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheltered_victims', to='infraestructura.shelter'),
        ),
    ]
